{{- if .Values.mautic.cron.import.enabled }}
kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ include "mautic.fullname" . }}-import
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: "{{ .Values.mautic.cron.import.schedule }}"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: console
            image: "{{ .Values.mautic.image.repository }}:console-{{ .Values.mautic.image.tag }}"
            imagePullPolicy: "{{ .Values.mautic.image.pullPolicy }}"
            args:
              - mautic:import
              {{- if .Values.mautic.cron.import.limit }}
              - --limit
              - "{{ .Values.mautic.cron.import.limit }}"
              {{- end }}
            envFrom:
              {{- include "mautic.envFrom" . | nindent 14 }}
            {{- if .Values.mautic.cron.import.env }}
            env:
              {{- toYaml .Values.mautic.cron.import.env | nindent 14 }}
            {{- end }}
            volumeMounts:
              {{- include "mautic.volumeMounts" . | nindent 14 }}
            resources:
              {{- toYaml .Values.mautic.cron.import.resources | nindent 14 }}
          restartPolicy: OnFailure
          volumes:
            {{- include "mautic.volumes" . | nindent 12 }}
{{- end }}
---
{{- if .Values.mautic.cron.segmentsUpdate.enabled }}
kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ include "mautic.fullname" . }}-segments-update
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: "{{ .Values.mautic.cron.segmentsUpdate.schedule }}"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: console
            image: "{{ .Values.mautic.image.repository }}:console-{{ .Values.mautic.image.tag }}"
            imagePullPolicy: "{{ .Values.mautic.image.pullPolicy }}"
            args:
              - mautic:segments:update
              {{- if .Values.mautic.cron.segmentsUpdate.batchLimit }}
              - --batch-limit
              - "{{ .Values.mautic.cron.segmentsUpdate.batchLimit }}"
              {{- end }}
              {{- if .Values.mautic.cron.segmentsUpdate.maxContacts }}
              - --max-contacts
              - "{{ .Values.mautic.cron.segmentsUpdate.maxContacts }}"
              {{- end }}
              - --lock_mode
              - flock
            envFrom:
              {{- include "mautic.envFrom" . | nindent 14 }}
            {{- if .Values.mautic.cron.segmentsUpdate.env }}
            env:
              {{- toYaml .Values.mautic.cron.segmentsUpdate.env | nindent 14 }}
            {{- end }}
            volumeMounts:
              {{- include "mautic.volumeMounts" . | nindent 14 }}
            resources:
              {{- toYaml .Values.mautic.cron.import.resources | nindent 14 }}
          restartPolicy: OnFailure
          volumes:
            {{- include "mautic.volumes" . | nindent 12 }}
{{- end }}
---
{{- if .Values.mautic.cron.campaignsTrigger.enabled }}
kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ include "mautic.fullname" . }}-campaigns-trigger
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: "{{ .Values.mautic.cron.campaignsTrigger.schedule }}"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: console
            image: "{{ .Values.mautic.image.repository }}:console-{{ .Values.mautic.image.tag }}"
            imagePullPolicy: "{{ .Values.mautic.image.pullPolicy }}"
            args:
              - mautic:campaigns:trigger
              {{- if .Values.mautic.cron.campaignsTrigger.batchLimit }}
              - --batch-limit
              - "{{ .Values.mautic.cron.campaignsTrigger.batchLimit }}"
              {{- end }}
              {{- if .Values.mautic.cron.campaignsTrigger.campaignLimit }}
              - --campaign-limit
              - "{{ .Values.mautic.cron.campaignsTrigger.campaignLimit }}"
              {{- end }}
              - --lock_mode
              - flock
            envFrom:
              {{- include "mautic.envFrom" . | nindent 14 }}
            {{- if .Values.mautic.cron.campaignsTrigger.env }}
            env:
              {{- toYaml .Values.mautic.cron.campaignsTrigger.env | nindent 14 }}
            {{- end }}
            volumeMounts:
              {{- include "mautic.volumeMounts" . | nindent 14 }}
            resources:
              {{- toYaml .Values.mautic.cron.import.resources | nindent 14 }}
          restartPolicy: OnFailure
          volumes:
            {{- include "mautic.volumes" . | nindent 12 }}
{{- end }}
---
{{- if .Values.mautic.cron.campaignsSummarize.enabled }}
kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ include "mautic.fullname" . }}-campaigns-summarize
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: "{{ .Values.mautic.cron.campaignsSummarize.schedule }}"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: console
            image: "{{ .Values.mautic.image.repository }}:console-{{ .Values.mautic.image.tag }}"
            imagePullPolicy: "{{ .Values.mautic.image.pullPolicy }}"
            args:
              - mautic:campaigns:summarize
              {{- if .Values.mautic.cron.campaignsSummarize.batchLimit }}
              - --batch-limit
              - "{{ .Values.mautic.cron.campaignsSummarize.batchLimit }}"
              {{- end }}
              {{- if .Values.mautic.cron.campaignsSummarize.maxHours }}
              - --max-hours
              - "{{ .Values.mautic.cron.campaignsSummarize.maxHours }}"
              {{- end }}
              {{- if .Values.mautic.cron.campaignsSummarize.rebuild }}
              - --rebuild
              {{- end }}
              - --lock_mode
              - flock
            envFrom:
              {{- include "mautic.envFrom" . | nindent 14 }}
            {{- if .Values.mautic.cron.campaignsSummarize.env }}
            env:
              {{- toYaml .Values.mautic.cron.campaignsSummarize.env | nindent 14 }}
            {{- end }}
            volumeMounts:
              {{- include "mautic.volumeMounts" . | nindent 14 }}
            resources:
              {{- toYaml .Values.mautic.cron.import.resources | nindent 14 }}
          restartPolicy: OnFailure
          volumes:
            {{- include "mautic.volumes" . | nindent 12 }}
{{- end }}
---
{{- if .Values.mautic.cron.campaignsRebuild.enabled }}
kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ include "mautic.fullname" . }}-campaigns-rebuild
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: "{{ .Values.mautic.cron.campaignsRebuild.schedule }}"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: console
            image: "{{ .Values.mautic.image.repository }}:console-{{ .Values.mautic.image.tag }}"
            imagePullPolicy: "{{ .Values.mautic.image.pullPolicy }}"
            args:
              - mautic:campaigns:rebuild
              {{- if .Values.mautic.cron.campaignsRebuild.batchLimit }}
              - --batch-limit
              - "{{ .Values.mautic.cron.campaignsRebuild.batchLimit }}"
              {{- end }}
              {{- if .Values.mautic.cron.campaignsRebuild.maxContacts }}
              - --max-contacts
              - "{{ .Values.mautic.cron.campaignsRebuild.maxContacts }}"
              {{- end }}
              - --lock_mode
              - flock
            envFrom:
              {{- include "mautic.envFrom" . | nindent 14 }}
            {{- if .Values.mautic.cron.campaignsRebuild.env }}
            env:
              {{- toYaml .Values.mautic.cron.campaignsRebuild.env | nindent 14 }}
            {{- end }}
            volumeMounts:
              {{- include "mautic.volumeMounts" . | nindent 14 }}
            resources:
              {{- toYaml .Values.mautic.cron.import.resources | nindent 14 }}
          restartPolicy: OnFailure
          volumes:
            {{- include "mautic.volumes" . | nindent 12 }}
{{- end }}
---
{{- if .Values.mautic.cron.broadcastsSend.enabled }}
kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ include "mautic.fullname" . }}-broadcasts-send
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: "{{ .Values.mautic.cron.broadcastsSend.schedule }}"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: console
            image: "{{ .Values.mautic.image.repository }}:console-{{ .Values.mautic.image.tag }}"
            imagePullPolicy: "{{ .Values.mautic.image.pullPolicy }}"
            args:
              - mautic:broadcasts:send
              - --lock_mode
              - flock
            envFrom:
              {{- include "mautic.envFrom" . | nindent 14 }}
            {{- if .Values.mautic.cron.broadcastsSend.env }}
            env:
              {{- toYaml .Values.mautic.cron.broadcastsSend.env | nindent 14 }}
            {{- end }}
            volumeMounts:
              {{- include "mautic.volumeMounts" . | nindent 14 }}
            resources:
              {{- toYaml .Values.mautic.cron.import.resources | nindent 14 }}
          restartPolicy: OnFailure
          volumes:
            {{- include "mautic.volumes" . | nindent 12 }}
{{- end }}
---
{{- if .Values.mautic.cron.messagesSend.enabled }}
kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ include "mautic.fullname" . }}-messages-send
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: "{{ .Values.mautic.cron.messagesSend.schedule }}"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: console
            image: "{{ .Values.mautic.image.repository }}:console-{{ .Values.mautic.image.tag }}"
            imagePullPolicy: "{{ .Values.mautic.image.pullPolicy }}"
            args:
              - mautic:messages:send
              - --lock_mode
              - flock
            envFrom:
              {{- include "mautic.envFrom" . | nindent 14 }}
            {{- if .Values.mautic.cron.messagesSend.env }}
            env:
              {{- toYaml .Values.mautic.cron.messagesSend.env | nindent 14 }}
            {{- end }}
            volumeMounts:
              {{- include "mautic.volumeMounts" . | nindent 14 }}
            resources:
              {{- toYaml .Values.mautic.cron.import.resources | nindent 14 }}
          restartPolicy: OnFailure
          volumes:
            {{- include "mautic.volumes" . | nindent 12 }}
{{- end }}
---
# mautic:contacts:scheduled_export
{{- if .Values.mautic.cron.contactsScheduledExport.enabled }}
kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ include "mautic.fullname" . }}-contacts-scheduled-export
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: "{{ .Values.mautic.cron.contactsScheduledExport.schedule }}"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: console
            image: "{{ .Values.mautic.image.repository }}:console-{{ .Values.mautic.image.tag }}"
            imagePullPolicy: "{{ .Values.mautic.image.pullPolicy }}"
            args:
              - mautic:contacts:scheduled_export
            envFrom:
              {{- include "mautic.envFrom" . | nindent 14 }}
            {{- if .Values.mautic.cron.contactsScheduledExport.env }}
            env:
              {{- toYaml .Values.mautic.cron.contactsScheduledExport.env | nindent 14 }}
            {{- end }}
            volumeMounts:
              {{- include "mautic.volumeMounts" . | nindent 14 }}
            resources:
              {{- toYaml .Values.mautic.cron.import.resources | nindent 14 }}
          restartPolicy: OnFailure
          volumes:
            {{- include "mautic.volumes" . | nindent 12 }}
{{- end }}