{{- if .Values.mautic.cron.import.enabled }}
kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ include "mautic.fullname" . }}-import
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: "{{ .Values.mautic.cron.import.schedule }}"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: console
            image: "{{ .Values.mautic.image.repository }}:console-{{ .Values.mautic.image.tag }}"
            imagePullPolicy: "{{ .Values.mautic.image.pullPolicy }}"
            args:
              - mautic:import
              {{- if .Values.mautic.cron.import.limit }}
              - --limit
              - "{{ .Values.mautic.cron.import.limit }}"
              {{- end }}
            envFrom:
              {{- include "mautic.envFrom" . | nindent 14 }}
            volumeMounts:
              {{- include "mautic.volumeMounts" . | nindent 14 }}
          restartPolicy: OnFailure
          volumes:
            {{- include "mautic.volumes" . | nindent 12 }}
{{- end }}
---
{{- if .Values.mautic.cron.segmentsUpdate.enabled }}
kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ include "mautic.fullname" . }}-segments-update
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: "{{ .Values.mautic.cron.segmentsUpdate.schedule }}"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: console
            image: "{{ .Values.mautic.image.repository }}:console-{{ .Values.mautic.image.tag }}"
            imagePullPolicy: "{{ .Values.mautic.image.pullPolicy }}"
            args:
              - mautic:segments:update
              {{- if .Values.mautic.cron.segmentsUpdate.batchLimit }}
              - --batch-limit
              - "{{ .Values.mautic.cron.segmentsUpdate.batchLimit }}"
              {{- end }}
              {{- if .Values.mautic.cron.segmentsUpdate.maxContacts }}
              - --max-contacts
              - "{{ .Values.mautic.cron.segmentsUpdate.maxContacts }}"
              {{- end }}
              - --lock_mode
              - flock
            envFrom:
              {{- include "mautic.envFrom" . | nindent 14 }}
            volumeMounts:
              {{- include "mautic.volumeMounts" . | nindent 14 }}
          restartPolicy: OnFailure
          volumes:
            {{- include "mautic.volumes" . | nindent 12 }}
{{- end }}