apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mautic.fullname" . }}
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "mautic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mautic.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mautic.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      enableServiceLinks: false
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.mautic.image.repository }}:web-{{ .Values.mautic.image.tag }}"
          imagePullPolicy: {{ .Values.mautic.image.pullPolicy }}
          envFrom:
            {{- include "mautic.envFrom" . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.mautic.web.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.mautic.web.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.mautic.web.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.mautic.web.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.mautic.web.startupProbe }}
          startupProbe:
            {{- toYaml .Values.mautic.web.startupProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.mautic.web.resources | nindent 12 }}
          volumeMounts:
            {{- include "mautic.volumeMounts" . | nindent 12 }}
      volumes: 
        {{- include "mautic.volumes" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
