apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mautic.fullname" . }}
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
    mautic/process: web
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "mautic.selectorLabels" . | nindent 6 }}
      mauitc/process: web
  template:
    metadata:
      labels:
        {{- include "mautic.labels" . | nindent 8 }}
        mautic/process: web
    spec:
      enableServiceLinks: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.mautic.image.repository }}:web-{{ .Values.mautic.image.tag }}"
          imagePullPolicy: {{ .Values.mautic.image.pullPolicy }}
          envFrom:
            {{- include "mautic.envFrom" . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.mautic.web.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.mautic.web.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.mautic.web.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.mautic.web.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.mautic.web.startupProbe }}
          startupProbe:
            {{- toYaml .Values.mautic.web.startupProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.mautic.web.resources | nindent 12 }}
          volumeMounts:
            {{- include "mautic.volumeMounts" . | nindent 12 }}
      {{- with .Values.mautic.web.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- range . }}
        - {{ . | toYaml | indent 10 | trim }}
          labelSelector:
            matchLabels:
              {{- include "mautic.selectorLabels" $ | nindent 14 }}
      {{- end }}
      {{- end }}
      volumes: 
        {{- include "mautic.volumes" . | nindent 8 }}
---
{{- if .Values.mautic.messenger.consumeEmail.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "mautic.fullname" . }}-messenger-consume-email
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
    mautic/process: messenger-consume-email
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "mautic.selectorLabels" . | nindent 6 }}
      mautic/process: messenger-consume-email
  template:
    metadata:
      labels:
        {{- include "mautic.labels" . | nindent 8 }}
        mautic/process: messenger-consume-email
    spec:
      enableServiceLinks: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.mautic.image.repository }}:console-{{ .Values.mautic.image.tag }}"
          imagePullPolicy: {{ .Values.mautic.image.pullPolicy }}
          args:
            - messenger:consume
            - email
            {{- if .Values.mautic.messenger.consumeEmail.debug }}
            - -vv
            {{- end }}
            {{- if .Values.mautic.messenger.consumeEmail.memoryLimit }}
            - --memory-limit
            - {{ .Values.mautic.messenger.consumeEmail.memoryLimit }}
            {{- end }}
          envFrom:
            {{- include "mautic.envFrom" . | nindent 12 }}
          volumeMounts:
            {{- include "mautic.volumeMounts" . | nindent 12 }}
          resources:
            {{- toYaml .Values.mautic.messenger.consumeEmail.resources | nindent 12 }}
      volumes:
        {{- include "mautic.volumes" . | nindent 8 }}
{{- end }}
---
{{- if .Values.mautic.messenger.consumeHit.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "mautic.fullname" . }}-messenger-consume-hit
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
    mautic/process: messenger-consume-hit
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "mautic.selectorLabels" . | nindent 6 }}
      mautic/process: messenger-consume-hit
  template:
    metadata:
      labels:
        {{- include "mautic.labels" . | nindent 8 }}
        mautic/process: messenger-consume-hit
    spec:
      enableServiceLinks: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.mautic.image.repository }}:console-{{ .Values.mautic.image.tag }}"
          imagePullPolicy: {{ .Values.mautic.image.pullPolicy }}
          args:
            - messenger:consume
            - hit
            {{- if .Values.mautic.messenger.consumeHit.debug }}
            - -vv
            {{- end }}
            {{- if .Values.mautic.messenger.consumeHit.memoryLimit }}
            - --memory-limit
            - {{ .Values.mautic.messenger.consumeHit.memoryLimit }}
            {{- end }}
          envFrom:
            {{- include "mautic.envFrom" . | nindent 12 }}
          volumeMounts:
            {{- include "mautic.volumeMounts" . | nindent 12 }}
          resources:
            {{- toYaml .Values.mautic.messenger.consumeHit.resources | nindent 12 }}
      volumes:
        {{- include "mautic.volumes" . | nindent 8 }}
{{- end }}
---
{{- if .Values.mautic.messenger.consumeFailed.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "mautic.fullname" . }}-messenger-consume-failed
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
    mautic/process: messenger-consume-failed
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "mautic.selectorLabels" . | nindent 6 }}
      mautic/process: messenger-consume-failed
  template:
    metadata:
      labels:
        {{- include "mautic.labels" . | nindent 8 }}
        mautic/process: messenger-consume-failed
    spec:
      enableServiceLinks: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.mautic.image.repository }}:console-{{ .Values.mautic.image.tag }}"
          imagePullPolicy: {{ .Values.mautic.image.pullPolicy }}
          args:
            - messenger:consume
            - failed
            {{- if .Values.mautic.messenger.consumeFailed.debug }}
            - -vv
            {{- end }}
            {{- if .Values.mautic.messenger.consumeFailed.memoryLimit }}
            - --memory-limit
            - {{ .Values.mautic.messenger.consumeFailed.memoryLimit }}
            {{- end }}
          envFrom:
            {{- include "mautic.envFrom" . | nindent 12 }}
          volumeMounts:
            {{- include "mautic.volumeMounts" . | nindent 12 }}
          resources:
            {{- toYaml .Values.mautic.messenger.consumeFailed.resources | nindent 12 }}
      volumes:
        {{- include "mautic.volumes" . | nindent 8 }}
{{- end }}