kind: Job
apiVersion: batch/v1
metadata:
  name: {{ include "mautic.fullname" . }}-install-{{ now | unixEpoch }}
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mautic.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mautic.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      enableServiceLinks: false
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.mautic.image.repository }}:install-{{ .Values.mautic.image.tag }}"
          args:
            - {{ .Values.mautic.install.siteUrl | quote }}
          imagePullPolicy: {{ .Values.mautic.image.pullPolicy }}
          envFrom:
            {{- include "mautic.envFrom" . | nindent 12 }}
          resources:
            {{- toYaml .Values.mautic.install.resources | nindent 12 }}
          volumeMounts:
            {{- include "mautic.volumeMounts" . | nindent 12 }}
      volumes:
        {{- include "mautic.volumes" . | nindent 8 }}
      restartPolicy: OnFailure
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}