kind: Job
apiVersion: batch/v1
metadata:
  name: {{ include "mautic.fullname" . }}-install-{{ now | unixEpoch }}
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
    mautic/process: install
spec:
  template:
    metadata:
      labels:
        {{- include "mautic.labels" . | nindent 8 }}
        mautic/process: install
    spec:
      enableServiceLinks: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.mautic.image.repository }}:install-{{ .Values.mautic.image.tag }}"
          args:
            - {{ .Values.mautic.install.siteUrl | quote }}
          imagePullPolicy: {{ .Values.mautic.image.pullPolicy }}
          envFrom:
            {{- include "mautic.envFrom" . | nindent 12 }}
          resources:
            {{- toYaml .Values.mautic.install.resources | nindent 12 }}
          volumeMounts:
            {{- include "mautic.volumeMounts" . | nindent 12 }}
      volumes:
        {{- include "mautic.volumes" . | nindent 8 }}
      restartPolicy: OnFailure