{{- if .Values.mautic.web.vpa.enabled }}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "mautic.fullname" . }}
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: {{ include "mautic.fullname" . }}
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: ["memory"]
        minAllowed: 
          memory: {{ .Values.mautic.web.vpa.minMemory }}
        maxAllowed:
          memory: {{ .Values.mautic.web.vpa.maxMemory }}
{{- end }}