nameOverride: ""
fullnameOverride: ""

mautic:
  image:
    repository: tanjim/mautic
    pullPolicy: IfNotPresent
    tag: "5.1.16"

  # existingConfigMap: ""
  # ignore the following values if existingConfigMap is set
  configMap:
    # optional, if siteUrl is set in install
    # SITE_URL: "https://localhost:8080"
    # messenger
    MAUTIC_MESSENGER_DSN_EMAIL: "doctrine://default"
    MAUTIC_MESSENGER_DSN_HIT: "doctrine://default"
  
  # existingSecret: ""
  # ignore the following values if existingSecret is set
  secret:
    # admin
    MAUTIC_ADMIN_USERNAME: "admin"
    MAUTIC_ADMIN_EMAIL: "contact@example.com"
    MAUTIC_ADMIN_PASSWORD: "admin"
    # mailer
    # MAUTIC_MAILER_DSN: "smtp://user:pass@localhost:587"

  persistence:
    accessMode: ReadWriteMany
    # example: efs, nfs, etc.
    # storageClass: "nfs"

  web:
    resources:
      limits:
        memory: 384Mi
      requests:
        cpu: 200m
        memory: 256Mi
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 10
      targetCPU: 80
    vpa:
      enabled: false
      minMemory: 128Mi
      maxMemory: 1024Mi
    readinessProbe: &probe
      # check if request to /s/login returns 301 (redirect) status code
      exec:
        command: 
          - sh
          - -c
          - |
            if [ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost/s/login)" != "301" ]; then
              exit 1
            fi
      timeoutSeconds: 2
    livenessProbe:
      <<: *probe
      timeoutSeconds: 10
    startupProbe:
      <<: *probe
      failureThreshold: 30
      periodSeconds: 10

  install:
    # optional, if SITE_URL is not set in configMap
    siteUrl: "https://localhost:8080"
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi

  db:
    create: true
    # existingConfigMap: ""
    # ignore the following values if existingConfigMap is set
    configMap:
      MAUTIC_DB_HOST: mysql
      # MAUTIC_DB_HOST_RO: mysql-ro
      MAUTIC_DB_PORT: "3306"
      MAUTIC_DB_NAME: mautic

    # existingSecret: ""
    # ignore the following values if existingSecret is set
    secret:
      MAUTIC_DB_USER: mautic
      MAUTIC_DB_PASSWORD: mautic
  
  cron:
    import:
      enabled: true
      schedule: "*/6 * * * *"
      # limit: 5000
    campaignsRebuild:
      enabled: true
      schedule: "*/5 * * * *"
      # batchLimit: 5000
      # maxContacts: 5000
    segmentsUpdate:
      enabled: true
      schedule: "*/4 * * * *"
      # batchLimit: 5000
      # maxContacts: 5000
    campaignsTrigger:
      enabled: true
      schedule: "*/3 * * * *"
      # batchLimit: 5000
    broadcastsSend:
      enabled: true
      schedule: "*/2 * * * *"
    messagesSend:
      enabled: true
      schedule: "*/1 * * * *"
  
  messenger:
    consumeEmail:
      enabled: true
    consumeFailed:
      enabled: true
    consumeHit:
      enabled: true

service:
  type: ClusterIP
  port: 80
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600

ingress:
  enabled: enabled
  # className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

